### ISSUE TITLE
Can't login to gitlab-ci after upgrading to 7.7.1 / 5.4.1 with http status 500

### ISSUE THREAD

**Issue by michaKFromParis** [sameersbn/docker-gitlab-ci#14]
Hi sameer,

I just upgraded gitlab to 7.7.0 and to 7.7.1 shortly after. Did the same with gitlab-ci.
I took good note of the 2 new variables GITLAB_APP_ID & GITLAB_APP_SECRET and configured them correctly in the run command of gitlab-ci after creating the application in the gitlab admin panel.
I've set the callback url to the one gitlab-ci provided me when these variables were not configured.
When I access gitlab-ci, it offers me to login with the gitlab api and redirects me to this authorization page on gitlab:

![screen shot 2015-01-23 at 2 28 47 pm](https://cloud.githubusercontent.com/assets/797836/5875335/489695fa-a30c-11e4-8b3b-c13e516c4e46.png)

If I click Authorize, gitlab call the callback url with the code variable defined but I land on a 500.

Did I miss something?

Best Regards and thanks for keeping your Docker builds so fresh all the time.

M

**Comment by michaKFromParis** [comment]
After a bit of digging into the gitlab-ci production.log, I found out this is related to my self signed SSL certificates:

Completed 500 Internal Server Error in 10ms

Faraday::SSLError (SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed):
  app/controllers/user_sessions_controller.rb:18:in `callback'

the variables are defined as follows and have always been working so far:

      -e 'GITLAB_CI_HTTPS=true' -e 'SSL_SELF_SIGNED=true' \

I'll dig a bit deeper to find out the reason why it stopped working.

**Comment by sameersbn** [comment]
@michaKFromParis You need to trust your gitlab servers ssl certificate https://github.com/sameersbn/docker-gitlab

**Comment by sameersbn** [comment]
@michaKFromParis p.s. the same can also be configured for gitlab so that gitlab-ci's ssl certificate is trusted by the gitlab server.

**Comment by michaKFromParis** [comment]
Thanks sameer, Are you referring to the section "Installing Trusted SSL
Server Certificates" ?


On Friday, January 23, 2015, Sameer Naik <notifications@github.com> wrote:

> @michaKFromParis <https://github.com/michaKFromParis> p.s. the same can
> also be configured for gitlab so that gitlab-ci's ssl certificate is
> trusted by the gitlab server.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sameersbn/docker-gitlab-ci/issues/14#issuecomment-71206630>
> .
>


-- 
Michel Courtine | CEO | iVoltage
+33 6 189 354 89 | michaK@ivoltage.me
http://ivoltage.me

**Comment by sameersbn** [comment]
@michaKFromParis yes

**Comment by michaKFromParis** [comment]
All good in the hood! Thanks

**Comment by michaKFromParis** [comment]
Further comments here:

https://gitlab.com/gitlab-org/gitlab-ci/issues/93#note_768111

**Comment by danger89** [comment]
The correct answer was to append our own self-signed certificate to the cert.pem, see:
https://gitlab.com/gitlab-org/gitlab-ci/issues/89#note_1594051
