### ISSUE TITLE
Variable environments

### ISSUE THREAD

**Issue by brunobatista** [sameersbn/docker-gitlab-ci#16]
Hey, where I find this variables `GITLAB_APP_ID` and `GITLAB_APP_SECRET`? Thanks.

**Comment by cedvan** [comment]
Hello,

- Go in Gitlab Settings
- Add an application
- Enter name **gitlab CI**
- Enter redirect url **https://your_host_gitlab_ci/user_sessions/callback**
- Submit

Have fun ;)

**Comment by brunobatista** [comment]
Thanks @cedvan to try help. I can not see this option on my gitlab.

My gitlab info:
```
GitLab 7.3.1
GitLab Shell 2.0.0
GitLab API v3
Ruby 2.1.2p95
Rails 4.1.1
```

**Comment by cedvan** [comment]
Look requirements, Gitlab CI v5.4 need Gitlab v7.7.0 or newer !

Update your Gitlab ;)

**Comment by brunobatista** [comment]
Thanls @cedvan :+1:
