### ISSUE TITLE
Cronjob for scheduled builds not working

### ISSUE THREAD

**Issue by fruel** [sameersbn/docker-gitlab-ci#21]
I have successfully set up Gitlab CI 7.9.1 with Docker 1.5.0 on Ubuntu 14.04. Everything seems to be working fine (webinterface, builds on commit triggered by Gitlab, ...) except scheduled builds. 

In my project settings I enabled ```Repeat last build after X hours if no builds``` and set the time to 2 hours. Gitlab CI still starts a build only on commits and not every 2 hours.

Cron is running and the conjob for the ```gitlab-ci``` user exists.
When I execute the commend that is defined in the crontab file manually the scheduler works correctly and starts a build if necessary.

/var/spool/cron/crontabs/gitlab_ci (inside the docker instance)
```
# DO NOT EDIT THIS FILE - edit the master and reinstall.
# (/tmp/whenever_tmp_cron20150326-2030-114jykx installed on Thu Mar 26 11:34:36 2015)
# (Cron version -- $Id: crontab.c,v 2.13 1994/01/17 03:20:37 vixie Exp $)
# Begin Whenever generated tasks for: /home/gitlab_ci/gitlab-ci/config/schedule.rb
0 * * * * /bin/bash -l -c 'cd /home/gitlab_ci/gitlab-ci && RAILS_ENV=production bundle exec rake schedule_builds --silent'


# End Whenever generated tasks for: /home/gitlab_ci/gitlab-ci/config/schedule.rb
```

ps auxf (inside the docker instance)
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root      2828  1.0  0.0  18144  1888 ?        S    19:44   0:00 bash
root      2842  0.0  0.0  15560  1120 ?        R+   19:44   0:00  \_ ps auxf
root         1  0.3  0.0  60576 13900 ?        Ss   19:43   0:00 /usr/bin/python /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf
gitlab_+  2760  8.9  0.6 2299860 102680 ?      Sl   19:43   0:08 sidekiq 2.17.0 gitlab-ci [0 of 25 busy]
gitlab_+  2761  8.6  0.6 276836 100012 ?       Sl   19:43   0:08 unicorn_rails master -c /home/gitlab_ci/gitlab-ci/config/unicorn.rb -E production
gitlab_+  2778 12.5  1.0 349076 165320 ?       Sl   19:43   0:11  \_ unicorn_rails worker[0] -c /home/gitlab_ci/gitlab-ci/config/unicorn.rb -E production
gitlab_+  2782  0.7  0.6 279876 100764 ?       Sl   19:43   0:00  \_ unicorn_rails worker[1] -c /home/gitlab_ci/gitlab-ci/config/unicorn.rb -E production
root      2762  0.0  0.0  23652  1080 ?        S    19:43   0:00 /usr/sbin/cron -f
root      2763  0.0  0.0 100508  4708 ?        S    19:43   0:00 nginx: master process /usr/sbin/nginx -g daemon off;
www-data  2766  0.0  0.0 101224  3388 ?        S    19:43   0:00  \_ nginx: worker process
```

Edit:
A workaround is to run it as cronjob on the docker host:
```0 * * * * docker exec gitlab-ci sudo -u gitlab_ci /bin/bash -l -c 'cd /home/gitlab_ci/gitlab-ci && RAILS_ENV=production bundle exec rake schedule_builds --silent'```

**Comment by sameersbn** [comment]
@fruel I am guessing that the `PATH` variable is not set correctly when cronjob executes. I will try this out later.

**Comment by LordFPL** [comment]
I confim, it's working with : 
```
/bin/bash -c 'cd /home/gitlab_ci/gitlab-ci && PATH=/usr/local/bin:/usr/bin:/bin RAILS_ENV=production bundle exec rake schedule_builds --silent'
```

**Comment by sameersbn** [comment]
Sorry for not getting to this. Will make sure this is part of the upcoming release
