### ISSUE TITLE
docker-compose: Database Issues

### ISSUE THREAD

**Issue by DSchalla** [sameersbn/docker-gitlab-ci#25]
Hello there,

first of all thanks a lot for the creation of the docker images, using the Gitlab Image since a few days and it works flawless.

I wanted to integrate the Gitlab CI Image now to my setup, however when I copy&paste your configuration from the image and try docker-compose up I run into the following issue:

-> # docker-compose up   
Creating ci_postgresql_1...
Creating ci_redis_1...
Creating ci_ci_1...
Attaching to ci_postgresql_1, ci_redis_1, ci_ci_1
postgresql_1 | |------------------------------------------------------------------|
postgresql_1 | | PostgreSQL User: postgres, Password: xxxxxxxxxx              |
postgresql_1 | |                                                                  |
postgresql_1 | | To remove the PostgreSQL login credentials from the logs, please |
postgresql_1 | | make a note of password and then delete the file pwfile          |
postgresql_1 | | from the data store.                                             |
postgresql_1 | |------------------------------------------------------------------|
postgresql_1 | Creating user "gitlab_ci"...
postgresql_1 | Creating database "gitlab_ci_production"...
postgresql_1 | Granting access to database "gitlab_ci_production" for user "gitlab_ci"...
postgresql_1 | Starting PostgreSQL server...
postgresql_1 | 2015-04-24 17:08:20 UTC [74-1] LOG:  database system was shut down at 2015-04-24 17:08:20 UTC
postgresql_1 | 2015-04-24 17:08:20 UTC [78-1] LOG:  autovacuum launcher started
postgresql_1 | 2015-04-24 17:08:20 UTC [73-1] LOG:  database system is ready to accept connections
ci_1         | Waiting for database server to accept connections..
ci_1         | Setting up GitLab CI for firstrun. Please be patient, this could take a while...
postgresql_1 | 2015-04-24 17:08:23 UTC [82-1] gitlab_ci@postgres ERROR:  database "gitlab_ci_production" already exists
postgresql_1 | 2015-04-24 17:08:23 UTC [82-2] gitlab_ci@postgres STATEMENT:  CREATE DATABASE "gitlab_ci_production" ENCODING = 'unicode'
ci_1         | gitlab_ci_production already exists
ci_1         | rake aborted!
ci_1         | Psych::SyntaxError: (<unknown>): did not find expected key while parsing a block mapping at line 3 column 5
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:103:in `initialize'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `new'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `instance'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:37:in `[]'
ci_1         | /home/gitlab_ci/gitlab-ci/config/initializers/1_settings.rb:32:in `<top (required)>'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:241:in `load'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:241:in `block in load'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:241:in `load'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/engine.rb:648:in `block in load_config_initializer'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/notifications.rb:161:in `instrument'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/engine.rb:647:in `load_config_initializer'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/engine.rb:611:in `each'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/engine.rb:611:in `block in <class:Engine>'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/initializable.rb:30:in `instance_exec'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/initializable.rb:30:in `run'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/initializable.rb:55:in `block in run_initializers'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/initializable.rb:44:in `each'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/initializable.rb:44:in `tsort_each_child'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/initializable.rb:54:in `run_initializers'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/application.rb:300:in `initialize!'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/railtie.rb:194:in `public_send'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/railtie.rb:194:in `method_missing'
ci_1         | /home/gitlab_ci/gitlab-ci/config/environment.rb:5:in `<top (required)>'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `block in require'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/application.rb:276:in `require_environment!'
ci_1         | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/application.rb:405:in `block in run_tasks_blocks'
ci_1         | Tasks: TOP => db:setup => db:schema:load_if_ruby => environment
ci_1         | (See full trace by running task with --trace)
ci_ci_1 exited with code 1
Gracefully stopping... (press Ctrl+C again to force)
Stopping ci_redis_1...
Stopping ci_postgresql_1...
Exception in thread Thread-1 (most likely raised during interpreter shutdown):#

Anyone has an idea what could be the issue? It seems that postgresql and gitlab want to create the database for the CI, however, I got no idea how to avoid that issue.

My docker-compose file looks like the one in the repo, just adjusted URLs + Tokens, and the PostgreSQL password.

**Comment by cbankester** [comment]
I'm getting this too. Might be easier to run the migrations on the db before starting the container.

**Comment by sameersbn** [comment]
@DSchalla @cbankester can you describe your setup. i.e. host distro, docker version and possibly share the `docker-compose.yml` file in use

**Comment by cbankester** [comment]
Sure! Note that I redacted the personally-identifying bits like hostnames and passwords.
```yaml
ci:
  image: sameersbn/gitlab-ci:7.10.1
  external_links:
    - gitlab_web_1:gitlab
    - gitlab_redis_1:redisio
  ports:
    - "10080:80"
  environment:
    - GITLAB_CI_HOST=gitlab-ci.[gitlab_domain]
    - GITLAB_CI_PORT=443
    - GITLAB_CI_HTTPS=true
    - GITLAB_APP_ID='[gitlab_app_id]'
    - GITLAB_APP_SECRET='[gitlab_app_secret]'
    - NGINX_MAX_UPLOAD_SIZE=100M
    - DB_TYPE=postgres
    - DB_HOST=[db_host_ip_address]
    - DB_NAME=gitlab_ci_production
    - DB_USER=gitlab_ci
    - DB_PASS=[db_password]
    - SMTP_HOST=client.[smtp_domain]
    - SMTP_DOMAIN=[smtp_domain]
    - SMTP_USER=smtp@client.[smtp_domain]
    - SMTP_PASS=[smtp_password]
```

Basically my setup is this:
* Gitlab running in docker container (https://github.com/sameersbn/docker-gitlab)
  - Note that the Gitlab `docker-compose.yml` uses `GITLAB_HOST=gitlab.[gitlab_domain]`, so it's on the same domain as Gitlab CI
* Redis container running alongside Gitlab container (specified in the Gitlab `docker-compose.yml`)
* Postgres DB running on an external server (`db_host_ip_address` above)

Since my last post, I've gotten Gitlab CI running manually on a different server, and I was able to build the DB (on the external DB server, same as the one being specified here). Now my stack trace is a little different:

```
[root@gitlab gitlab-ci]# docker-compose up
Creating gitlabci_ci_1...
Attaching to gitlabci_ci_1
ci_1 | SSL keys and certificates were not found.
ci_1 | Assuming that the container is running behind a HTTPS enabled load balancer.
ci_1 | Waiting for database server to accept connections
ci_1 | Migrating database...
ci_1 | rake aborted!
ci_1 | Psych::SyntaxError: (<unknown>): did not find expected key while parsing a block mapping at line 3 column 5
ci_1 | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:103:in `initialize'
ci_1 | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `new'
ci_1 | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `instance'
ci_1 | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:37:in `[]'
ci_1 | /home/gitlab_ci/gitlab-ci/config/initializers/1_settings.rb:32:in `<top (required)>'
ci_1 | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:241:in `load'
ci_1 | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:241:in `block in load'
ci_1 | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
ci_1 | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:241:in `load'
ci_1 | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/engine.rb:648:in `block in load_config_initializer'
ci_1 | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/notifications.rb:161:in `instrument'
ci_1 | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/engine.rb:647:in `load_config_initializer'
ci_1 | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
ci_1 | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/engine.rb:611:in `each'
ci_1 | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/engine.rb:611:in `block in <class:Engine>'
ci_1 | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/initializable.rb:30:in `instance_exec'
ci_1 | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/initializable.rb:30:in `run'
ci_1 | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/initializable.rb:55:in `block in run_initializers'
ci_1 | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/initializable.rb:44:in `each'
ci_1 | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/initializable.rb:44:in `tsort_each_child'
ci_1 | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/initializable.rb:54:in `run_initializers'
ci_1 | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/application.rb:300:in `initialize!'
ci_1 | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/railtie.rb:194:in `public_send'
ci_1 | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/railtie.rb:194:in `method_missing'
ci_1 | /home/gitlab_ci/gitlab-ci/config/environment.rb:5:in `<top (required)>'
ci_1 | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
ci_1 | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `block in require'
ci_1 | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
ci_1 | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
ci_1 | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/application.rb:276:in `require_environment!'
ci_1 | /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/application.rb:405:in `block in run_tasks_blocks'
ci_1 | Tasks: TOP => db:migrate => environment
ci_1 | (See full trace by running task with --trace)
```

**Comment by sameersbn** [comment]
@cbankester what is your host os?

**Comment by cbankester** [comment]
My apologies. I'm running:
* Docker 1.3.2
* CentOS 7

**Comment by DSchalla** [comment]
@sameersbn 

* Docker Compose from the Repo (Same file, exactly, just different DB Parameters)
* Docker version 1.5.0, build a8a31ef
* docker-compose 1.1.0
* Ubuntu 14.04.2 LTS

Thanks!

**Comment by cbankester** [comment]
@sameersbn @DSchalla I figured out what my issue was. In the `docker-compose.yml` file, single-quoting the app_id and app_secrets was leading to double-single-quoting of them in the container's `application.yml` file, which is invalid YAML syntax.

**Comment by sameersbn** [comment]
@DSchalla can you try @cbankester's resolution?

**Comment by sameersbn** [comment]
I have updated `docker-compose.yml` from the repo to remove the `'` characters in https://github.com/sameersbn/docker-gitlab-ci/commit/ed6702a33f27298212d319682d32bf1b440d320e

**Comment by sameersbn** [comment]
@DSchalla any updates?

**Comment by DSchalla** [comment]
Everything up and running @sameersbn, thanks a lot for your fix! Gitlab CI is running, I didn't try anything erious with it yet though. Feel free to close the issue.
