### ISSUE TITLE
not best follow

### ISSUE THREAD

**Issue by Haitianisgood** [sameersbn/docker-gitlab-ci#26]
docker pull sameersbn/gitlab-ci:latest
FATA[0000] Post http:///var/run/docker.sock/v1.18/images/create?fromImage=sameersbn%2Fgitlab-ci%3Alatest: dial unix /var/run/docker.sock: permission denied. Are you trying to connect to a TLS-enabled daemon without TLS?

**Comment by sameersbn** [comment]
@Haitianisgood I don't completely understand your issue due to the lack of information. But from your error message it looks like you do not have sufficient privileges to access the `/var/run/docker.sock` docker socket.  You probably need to use `sudo` to execute the command.

**Comment by Haitianisgood** [comment]
I know my error,I just want to say you command "docker pull sameersbn/gitlab-ci:latest " need right environment!But you didnt remind it!you should addd "sudo" or "sudo usermod -aG docker ubuntu"

**Comment by sameersbn** [comment]
@Haitianisgood well. Its difficult to cover every single aspect of docker here. Users are expected to know a fair bit of docker or at the very least read the error messages :smile:

**Comment by Haitianisgood** [comment]
yeah,you are right!but as ubuntu should come the same problems!I dont konw if you testing it!

**Comment by sameersbn** [comment]
@Haitianisgood I use 14.04 and I perform some basic tests.

**Comment by Haitianisgood** [comment]
I also use 14.04,and come across that problems.But thank you for you sharing!
