### ISSUE TITLE
Permission Issues

### ISSUE THREAD

**Issue by Thr1ve** [sameersbn/docker-gitlab-ci#32]
Hello!

When trying to run `$ docker-compose up` after copying your .yml into a directory, it fails with the following error message:

`ci_1         | mkdir: cannot create directory '/home/gitlab_ci/data/backups': Permission denied
gitlabcidocker_ci_1 exited with code 1`

I was able to get docker-gitlab up and running without problem, but can't seem to get past this issue with docker-gitlab-ci

I was able to find the below issues that I think might be related; however, I'm still new to this and struggling to make sense of it all. Not sure if I'm looking in the right direction or missing something obvious.

Possibly Related issues?
https://github.com/docker/docker/issues/1295
https://github.com/docker/docker/issues/783

**Docker version** :
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64

**Docker info**:
Containers: 6
Images: 244
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 256
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-45-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 8
Total Memory: 15.56 GiB

**Modified Portions of .yml**
  `ports:`
 `   - "8081:80"`
  `environment:`
  `  - GITLAB_URL=http://localhost:8080`
  `  - GITLAB_APP_ID=[id]`
  `  - GITLAB_APP_SECRET=[secret]`
 `   - GITLAB_CI_HOST=my.website.example.com`
  `  - GITLAB_CI_PORT=8081`

**Comment by sameersbn** [comment]
@Thr1ve can you retry with the `sameersbn/gitlab-ci:latest` image? I have made some changes that might fix the problem in cb28343b7aa640ce7973334e8c10ee90fd0d4616

**Comment by Thr1ve** [comment]
That worked! Thank you so much!

Closing Issue
