### ISSUE TITLE
ci_1: mkdir: cannot create directory '/home/gitlab_ci/data/backups': Permission denied

### ISSUE THREAD

**Issue by aplsms** [sameersbn/docker-gitlab-ci#33]
hi 
i have a problem runnyng docker-gitlab-ci
redis_1      | [9] 04 Jun 00:15:14.682 # Server started, Redis version 2.8.4
redis_1      | [9] 04 Jun 00:15:14.682 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1      | [9] 04 Jun 00:15:14.682 * The server is now ready to accept connections on port 6379
redis_1      | [9] 04 Jun 00:15:14.682 * The server is now ready to accept connections at /var/run/redis/redis.sock
ci_1         | mkdir: cannot create directory '/home/gitlab_ci/data/backups': Permission denied
dockergitlabci_ci_1 exited with code 1
Gracefully stopping... (press Ctrl+C again to force)
Stopping dockergitlabci_redis_1...
Stopping dockergitlabci_postgresql_1...
docker@boot2docker:~$ ls -la /srv/docker/gitlab-ci/
total 0
drwxr-xr-x    5 root     root           100 Jun  4 00:15 ./
drwxr-xr-x    4 root     root            80 Jun  4 00:15 ../
drwxr-xr-x    2 root     root            40 Jun  4 00:15 gitlab-ci/
----------------^^^^^^^^^^^^^
drwxr-xr-x    3 102      106             80 Jun  4 00:15 postgresql/
drwxr-xr-x    2 102      105             60 Jun  4 00:15 redis/

could you please take a look?

**Comment by sameersbn** [comment]
@aplsms This issue has been fixed in the `latest` tag. Can you try with that.

**Comment by aplsms** [comment]
got it, thank you,
