### ISSUE TITLE
Did the quick start w/ docker compose but no Instance Running 

### ISSUE THREAD

**Issue by chrisamoore** [sameersbn/docker-gitlab-ci#37]
I added an app in gitlab as well: 

I used the main ci url that it would be to generate the keys for the `docker-compose.yml` file

Output: 
![screen shot 2015-06-28 at 3 46 45 pm](https://cloud.githubusercontent.com/assets/740153/8398667/f5190e96-1dac-11e5-9e39-08f9f9a03716.png)
![screen shot 2015-06-28 at 3 46 37 pm](https://cloud.githubusercontent.com/assets/740153/8398670/040776ea-1dad-11e5-8dd3-a03b625f6498.png)
![screen shot 2015-06-28 at 3 46 27 pm](https://cloud.githubusercontent.com/assets/740153/8398671/0b341c70-1dad-11e5-88e7-2756b205cc2c.png)

Looks t be running... but there is no app on the front end. I am guessing no nginx ? ideas ?

**Comment by chrisamoore** [comment]
![screen shot 2015-06-28 at 3 50 52 pm](https://cloud.githubusercontent.com/assets/740153/8398681/81c813e6-1dad-11e5-9b3d-7a4ad073039c.png)

**Comment by chrisamoore** [comment]
![screen shot 2015-06-28 at 3 53 03 pm](https://cloud.githubusercontent.com/assets/740153/8398685/ce5ff23c-1dad-11e5-8e66-75f7aec27873.png)

**Comment by sameersbn** [comment]
@chrisamoore In you last screenshot i see host port `10081` is forwarded to port `81` of the container. This is incorrect, it should be forwarded to port `80`

**Comment by chrisamoore** [comment]
I had tried that and it faild as well, i ended up using the manual install :cry:

**Comment by chrisamoore** [comment]
Thanks though
