### ISSUE TITLE
doc - since 7.13.0 secrets env

### ISSUE THREAD

**Issue by jacek-marchwicki** [sameersbn/docker-gitlab-ci#41]
In README there is mentioned: 
`Since 7.13.0 you also need to provide the GITLAB_CI_SECRETS_SESSION_KEY_BASE and SECRETS_DB_KEY_BASE parameters.`

But there is no information how to generate those keys, can you point me a place where can I get such information.
I tried to find some informations in gitlab-ci documentation about secrets.yml but I failed

Btw: thanks for your great work ;)

**Comment by jacek-marchwicki** [comment]
@sameersbn sorry.. just after submitting I found your answer: https://github.com/sameersbn/docker-gitlab-ci/issues/1#issuecomment-123750651

**Comment by sameersbn** [comment]
@jacek-marchwicki thanks for pointing this out. I seemed to have missed documenting those parameters. updated the docs to include this information.
