### ISSUE TITLE
Cases where GITLAB_CI_PORT is not honnored

### ISSUE THREAD

**Issue by kyzh** [sameersbn/docker-gitlab-ci#45]
It seems that no matter what I set ```GITLAB_CI_PORT``` to, I have a hard time getting the port to be something else than 80 within the container.
I have a case where I run haproxy in front of gitlab-ci, therefore I don't provide certificates, yet I enable ```GITLAB_CI_HTTPS```.

**Comment by sameersbn** [comment]
@kyzh  the internal http server always runs on port 80. the `GITLAB_CI_PORT` is only used to perform http -> https redirection when the standard https port is not being used. .So in the docker run if you have `-p 10082:80 -e GITLAB_CI_PORT=10082` the gitlab ci http server will be accessible on port `10082` as per your configuration.

In short, the `GITLAB_CI_PORT` configuration does not change the port on which the internal nginx server listens for connections on.

**Comment by kyzh** [comment]
I think I got it.
Gitlab ci need to know which port (outside of the container here 10082) where https is served, so when one hit the http port, the redirect will provide the correct port for https(10082).
Both http and https are served over port 80 (within the container).
