### ISSUE TITLE
setting gitlab ci gravatar enabled configuration

### ISSUE THREAD

**Issue by lspvic** [sameersbn/docker-gitlab-ci#47]
It would be very nice that a GITLAB_CI_GRAVTAR_ENABLED enviroment variable added for the 'gravatar' option in application.yml, as gravatar.com is not available in some region thus leading a long loading gitlab-ci pages in browser. 

The configuration is as follows in application.yml:

> gravatar:
>       enabled: true    # this can be configured as {{GITLAB_CI_GRAVATAR_ENABLED}} 
>       plain_url: "http://www.gravatar.com/avatar/%{hash}?s=%{size}&d=mm"
>       ssl_url:   "https://secure.gravatar.com/avatar/%{hash}?s=%{size}&d=mm"

@sameersbn

**Comment by sameersbn** [comment]
Gitlab CI 7.14.0 has removed the gravatar configs all together.
