### ISSUE TITLE
postgres, select from projects: but tablename is ci_projects

### ISSUE THREAD

**Issue by sspreitzer** [sameersbn/docker-gitlab-ci#49]
Hi there

i found out that when using postgres it autocreates ci_* tablenames but in the code it is trying to access the tables without the prefix.
Looks like a bug to me. Configuration option is not available.

UPDATE: Don't know whether this issue should be filed to upstream.

Kind regards
Sascha

**Comment by sspreitzer** [comment]
"Since version 8.0 GitLab CI has been merged into GitLab CE and you no longer need to setup a separate GitLab CI instance."

Haven't read that, maybe thats why..

**Comment by sameersbn** [comment]
If its a new installation, you do not need to perform any CI migration steps. Just setup GitLab and thats all.
Please close the issue if resolved.

**Comment by sspreitzer** [comment]
Closing, works for me. Solution: Use sameersbn/docker-gitlab instead of sameersbn/docker-gitlab-ci.
