### ISSUE TITLE
ERROR:  database "gitlab_ci_production" already exists

### ISSUE THREAD

**Issue by miguelqvd** [sameersbn/docker-gitlab-ci#50]
Hi,

I'm using docker-compose to create one instance of your gitlab-ci image and since I started to try with version 8.0.4-1 the database can't be created:

postgresql_gitlab_ci_1 | 2015-10-11 19:58:48 UTC [87-1] gitlab_ci@postgres ERROR:  database "gitlab_ci_production" already exists
postgresql_gitlab_ci_1 | 2015-10-11 19:58:48 UTC [87-2] gitlab_ci@postgres STATEMENT:  CREATE DATABASE "gitlab_ci_production" ENCODING = 'unico

I've seen that the creation process is tried twice:
postgresql_gitlab_ci_1 | Initializing database...
postgresql_gitlab_ci_1 | Creating user "gitlab_ci"...
postgresql_gitlab_ci_1 | Creating database "gitlab_ci_production"...
postgresql_gitlab_ci_1 | Granting access to database "gitlab_ci_production" for user "gitlab_ci"...
postgresql_gitlab_ci_1 | Starting PostgreSQL server...
postgresql_gitlab_ci_1 | 2015-10-11 19:58:42 UTC [79-1] LOG:  database system was shut down at 2015-10-11 19:58:42 UTC
postgresql_gitlab_ci_1 | 2015-10-11 19:58:42 UTC [79-2] LOG:  MultiXact member wraparound protections are now enabled
postgresql_gitlab_ci_1 | 2015-10-11 19:58:42 UTC [1-1] LOG:  database system is ready to accept connections
postgresql_gitlab_ci_1 | 2015-10-11 19:58:42 UTC [83-1] LOG:  autovacuum launcher started
postgresql_gitlab_ci_1 | 2015-10-11 19:58:48 UTC [87-1] gitlab_ci@postgres ERROR:  database "gitlab_ci_production" already exists
postgresql_gitlab_ci_1 | 2015-10-11 19:58:48 UTC [87-2] gitlab_ci@postgres STATEMENT:  CREATE DATABASE "gitlab_ci_production" ENCODING = 'unico
here's my docker-compose.yml:

postgresql_gitlab_ci:
  image: quay.io/sameersbn/postgresql:latest
  environment:
    - DB_USER=gitlab_ci
    - DB_PASS=password
    - DB_NAME=gitlab_ci_production
  volumes:
    - /mnt/sda1/srv/gitlab-ci/postgresql:/var/lib/postgresql
redis_gitlab_ci:
  image: quay.io/sameersbn/redis:latest
  volumes:
    - /mnt/sda1/srv/gitlab-ci/redis:/var/lib/redis
gitlab_ci:
  image: quay.io/sameersbn/gitlab-ci:8.0.4-1
  links:
    - redis_gitlab_ci:redisio
    - postgresql_gitlab_ci:postgresql
  ports:
    - "10081:80"
    - "10444:443"
  environment:
    - TZ=Europe/Berlin
    - GITLAB_URL=http://192.168.99.100:10080
    - GITLAB_APP_ID=6513ce4328d17ec5f25d05ae4b336a0a2f999b48d0d4b82055391fd66e6ac2ee
    - GITLAB_APP_SECRET=e67f5ced58e8211c5a72483f50e350d8aa42d5454b346b627522d76c5092bd30
    - GITLAB_CI_SECRETS_SESSION_KEY_BASE=qjtLKX39WhL9zKtbLnch9bpkLwRfjKhVsWfnzVVzXtPwK4mNrcPcgbxXfCJVTKNX
    - GITLAB_CI_SECRETS_DB_KEY_BASE=XjxkgfPVkdgLxrmxzvbpL9wRv4vwbzcFJXns9vtTcNNT7tMzmR3VbmVxtPcsPwCN
    - GITLAB_CI_HOST=127.0.0.1
    - GITLAB_CI_PORT=10081
    - GITLAB_CI_EMAIL=ci@example.com
    - GITLAB_CI_SUPPORT=support@example.com
    - GITLAB_CI_NOTIFY_ON_BROKEN_BUILDS="true"
    - GITLAB_CI_NOTIFY_PUSHER=false
    - GITLAB_CI_BACKUPS=daily
    - GITLAB_CI_BACKUP_TIME=01:00
    - GITLAB_CI_HTTPS=false 
    - GITLAB_CI_HTTPS_ONLY=false
    - GITLAB_CI_HTTPS_HSTS_ENABLED=false
    - GITLAB_CI_HTTPS_HSTS_MAXAGE=2592000
    - SSL_KEY_PATH=/home/gitlab_ci/data/certs/gitlab.key
    - SSL_CERTIFICATE_PATH=/home/gitlab_ci/data/certs/gitlab.crt
    - SSL_DHPARAM_PATH=/home/gitlab_ci/data/certs/dhparam.pem
    - SSL_VERIFY=false 
    - SMTP_ENABLED=false
    - SMTP_DOMAIN=www.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login
  volumes:
    - /mnt/sda1/srv/gitlab-ci/data:/home/gitlab_ci/data
    - /mnt/sda1/srv/ca-certificates:/usr/local/share/ca-certificates

thank you in advance for your help and your great work!

**Comment by sameersbn** [comment]
Since version 8.0, Gitlab CI has been integrated into GitLab. The `8.0.x` versions of GitLab CI are meant for the purpose of migrating existing installations.

**Comment by miguelqvd** [comment]
Thank you so much!
